### ISSUE TITLE
Feature: User can view APOD(Astronomy-picture-of-the-day)

### ISSUE THREAD

**Issue by Hagop420** [Hagop420/ajax-project#1]
## ⚙️ Features
🖼️ Wireframes

![Image 11-28-23 at 2 03 PM](https://github.com/Hagop420/ajax-project/assets/81959688/01cfdd77-df37-4d73-a618-a40e2fffeb98)

![Image 11-28-23 at 2 04 PM](https://github.com/Hagop420/ajax-project/assets/81959688/f32c12c9-ff2e-4724-b7e1-66679f1a36ea)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a index.html file
- [x] Create a main tag which will contain the ajax APOD request
- [x] Underneath the main tag create a section which will contain the APOD title and it's explanation
- [x] Close the section tag
- [x] Style the header APOD and the section with css
- [x] Inside of the html file create the script files which will be targeting the NASA_API_javaScript files
- [x] Create the main.js file
- [x] Inside of main.js utilizing the XMLHttpRequest, make a request to https://api.nasa.gov/planetary/apod to retrieve the daily astronomy photo of the day.
- [x] Create a new function which appends the APOD image to the DOM
- [x] Add an event handler which will handle the AJAX request on a load event
- [x] Open the XMLHttpRequest with the Open method which takes in 3 parameters: the request type, the link pointing to the API, and a boolean.
- [x] Make sure the following responseType for the API is written with json format
- [x] Create a new image element
- [x] Give the image element an attribute containing the APOD image
- [x] Append the image element to the main tag in html
- [x] Call the send request on the XMLHttpRequest
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
